#Tomcat server port number 7070
server.port=8080
#context path default value : empty
server.servlet.context-path=/expense_tracker_hub
server.servlet.session.persistent=false

spring.datasource.url=jdbc:mysql://avnadmin:AVNS_b7dUOacnuznFxi4q8qa@mysql-adcd1f6-expense63.j.aivencloud.com:10351/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_b7dUOacnuznFxi4q8qa

# Driver class name for modern MySQL connectors
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

# Optional: Set the explicit SQL Dialect for MySQL 8+
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Optional: View generated SQL queries in the logs
spring.jpa.show-sql=true